---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jam-cluster
  region: us-east-1
  version: "1.30"

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t2.small
  ssh:
    enableSsm: true